from borrower import Borrower
from investor import Investor
from loan import Loan
from paymentFacade import PaymentFacade
from lenmoSingleton import Lenmo

borrower = Borrower(balance=100000)
investor = Investor(balance=2000000)
loan = Loan()
loan.submitLoanRequest(borrower=borrower, amount=500000, installment_period=6)
loan.showLoanReqDetails()
loan.submitLoanOffer(investor, 15)
loan.showLoanOffers()
offerId = loan.offers[0].id
loan.acceptLoanOffer(id=offerId)
borrower.checkMyLoanRequests()
investor.showMyOffers()
investor.showMyAcceptedOffers()
transaction = PaymentFacade(loan)
transaction.fundLoan()
print('lenmo balance increased by 3 $ paid by Investor')
print('lenmo balance: ', Lenmo().balance)
print('borrower balance =', borrower.balance)
print('borrower outstanding balance is =', borrower.outstanding)
print('investor balance =', investor.balance)
print('investor outstanding balance is =', investor.outstanding)
print('\n PAYMENT SCHEDULE'+'-'*30)
transaction.showPaymentSchedule()

print('\n First Transaction'+'-'*30)
transaction.doMonthlyPayment()
print('\n showPaidSchedule '+'-'*30)
transaction.showPaidSchedule()
print('\n showToPaySchedule '+'-'*30)
transaction.showToPaySchedule()

print('\n Second Transaction'+'-'*30)
transaction.doMonthlyPayment()
print('\n showPaidSchedule '+'-'*30)
transaction.showPaidSchedule()
print('\n showToPaySchedule '+'-'*30)
transaction.showToPaySchedule()

print('\n Third Transaction'+'-'*30)
transaction.doMonthlyPayment()
print('\n showPaidSchedule '+'-'*30)
transaction.showPaidSchedule()
print('\n showToPaySchedule '+'-'*30)
transaction.showToPaySchedule()

print('\n Fourth Transaction'+'-'*30)
transaction.doMonthlyPayment()
print('\n showPaidSchedule '+'-'*30)
transaction.showPaidSchedule()
print('\n showToPaySchedule '+'-'*30)
transaction.showToPaySchedule()

print('\n Fifth Transaction'+'-'*30)
transaction.doMonthlyPayment()
print('\n showPaidSchedule '+'-'*30)
transaction.showPaidSchedule()
print('\n showToPaySchedule '+'-'*30)
transaction.showToPaySchedule()

print('\n Last Transaction'+'-'*30)
transaction.doMonthlyPayment()
print('\n showPaidSchedule '+'-'*30)
transaction.showPaidSchedule()
print('\n showToPaySchedule '+'-'*30)
transaction.showToPaySchedule()
print(transaction.getLoanStatus())
print('lenmo balance: ', Lenmo().balance)
print('borrower balance =', borrower.balance)
print('borrower outstanding balance is =', int(borrower.outstanding))
print('investor balance =', investor.balance)
print('investor outstanding balance is =', int(investor.outstanding))
